import type { Metadata } from "next";
import { Nunito_Sans } from "next/font/google";
import "./globals.css";
import { Suspense } from "react";
import LoadingComponent from "./loading";

const nunitoNunito_Sans = Nunito_Sans({
	variable: "--font-nunito-sans",
	subsets: ["latin"],
	weight: ["200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en" suppressHydrationWarning>
			<body className={`dark ${nunitoNunito_Sans.variable} antialiased`}>
				<Suspense fallback={<LoadingComponent />}>{children}</Suspense>
			</body>
		</html>
	);
}
